package main.com.bsuir.autoservice.command.crud.get;

import com.google.inject.Inject;
import main.com.bsuir.autoservice.bean.Bean;
import main.com.bsuir.autoservice.command.ICommand;
import main.com.bsuir.autoservice.command.exception.CommandException;
import main.com.bsuir.autoservice.command.param.BeanAddPageInfo;
import main.com.bsuir.autoservice.dao.database.map.IDatabaseMap;
import main.com.bsuir.autoservice.service.unitofwork.IServiceUnitOfWork;

import java.util.Map;

public class GetBeanAddPageCommand implements ICommand<BeanAddPageInfo, BeanAddPageInfo> {

    @Inject
    public GetBeanAddPageCommand(IServiceUnitOfWork serviceUnitOfWork, IDatabaseMap databaseMap){
        this.serviceUnitOfWork = serviceUnitOfWork;
        this.databaseMap = databaseMap;
    }

    @Override
    public BeanAddPageInfo execute(BeanAddPageInfo beanAddPageInfo) throws CommandException {
        try {
            Bean<Object> bean = databaseMap.getBeanInstance(beanAddPageInfo.tableName);
            beanAddPageInfo.fields = bean.getFieldValuesStrings();
            for(Map.Entry<String, String> entry : beanAddPageInfo.defaultValues.entrySet()){
                beanAddPageInfo.fields.put(entry.getKey(), entry.getValue());
            }
            for(String autoField : bean.getAutoGeneratedFields()){
                beanAddPageInfo.fields.remove(autoField);
            }

            beanAddPageInfo.action = "add";
            return beanAddPageInfo;
        }catch (Exception e){
            throw new CommandException(e);
        }
    }

    private final IServiceUnitOfWork serviceUnitOfWork;
    private final IDatabaseMap databaseMap;
}
