package main.com.bsuir.autoservice.bean.impl;

import main.com.bsuir.autoservice.bean.Bean;
import main.com.bsuir.autoservice.bean.exception.BeanException;

import javax.lang.model.type.NullType;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class DiscountUser extends Bean<NullType> {

    public int getDiscountId(){
        return discount_id;
    }

    public void setDiscountId(int value){
        this.discount_id = value;
    }

    public int getUserId(){
        return user_id;
    }

    public void setUserId(int value){
        this.user_id = value;
    }

    @Override
    public Field[] getFieldsOrdered() throws BeanException {
        try {
            Class type = this.getClass();
            Field[] fields = {
                    type.getDeclaredField("discount_id"),
                    type.getDeclaredField("user_id")
            };
            for (Field field: fields) {
                field.setAccessible(true);
            }
            return fields;
        }catch (Exception e){
            throw new BeanException(e);
        }
    }

    public List<String> getAutoGeneratedFields() throws BeanException{
        List<String> strings = new ArrayList<>();
        return strings;
    }

    @Override
    public DiscountUser setFields(Map<String, String> fieldValues) {
        discount_id = Integer.valueOf(fieldValues.get("discount_id"));
        user_id = Integer.valueOf(fieldValues.get("user_id"));
        return this;
    }

    @Override
    public Field[] getRenderFields() throws BeanException{
        return getFieldsOrdered();
    }

    @Override
    public NullType getId() {
        return null;
    }

    private int discount_id;
    private int user_id;
}
