package main.com.bsuir.autoservice.bean.impl;

import main.com.bsuir.autoservice.bean.Bean;
import main.com.bsuir.autoservice.bean.exception.BeanException;

import main.com.bsuir.autoservice.library.type.date.SimpleDate;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class payment extends Bean{

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId_order() {
        return id_order;
    }

    public void setId_order(Integer id_order) {
        this.id_order = id_order;
    }

    public Integer getId_sender() {
        return id_sender;
    }

    public void setId_sender(Integer id_sender) {
        this.id_sender = id_sender;
    }

    public Integer getId_report() {
        return id_report;
    }

    public void setId_report(Integer id_report) {
        this.id_report = id_report;
    }

    public Integer getSum() {
        return sum;
    }

    public void setSum(Integer sum) {
        this.sum = sum;
    }

    public SimpleDate getDate() {
        return date;
    }

    public void setDate(SimpleDate date) {
        this.date = date;
    }

    @Override
    public Field[] getFieldsOrdered() throws BeanException {
        try {
            Class type = this.getClass();
            Field[] fields = {
                    type.getDeclaredField("id"),
                    type.getDeclaredField("id_order"),
                    type.getDeclaredField("id_sender"),
                    type.getDeclaredField("id_report"),
                    type.getDeclaredField("sum"),
                    type.getDeclaredField("date"),
            };
            for (Field field: fields) {
                field.setAccessible(true);
            }
            return fields;
        }catch (Exception e){
            throw new BeanException(e);
        }
    }

    public List<String> getAutoGeneratedFields() throws BeanException{
        List<String> strings = new ArrayList<>();
        strings.add("id");
        return strings;
    }

    @Override
    public payment setNotAutoGeneratedFields(Map<String, String> fieldValues) throws BeanException{
        try {
            id_order = Integer.valueOf(fieldValues.get("id_order"));
            id_sender = Integer.valueOf(fieldValues.get("id_sender"));
            id_report = Integer.valueOf(fieldValues.get("id_report"));
            sum = Integer.valueOf(fieldValues.get("sum"));
            date = new SimpleDate("date");
            return this;
        }catch (Exception e){
            throw new BeanException(e);
        }
    }

    private Integer id;
    private Integer id_order;
    private Integer id_sender;
    private Integer id_report;
    private Integer sum;
    private SimpleDate date;
}
