package main.com.bsuir.autoservice.bean.impl;

import main.com.bsuir.autoservice.bean.Bean;
import main.com.bsuir.autoservice.bean.exception.BeanException;


import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class phone extends Bean{

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId_operator() {
        return id_operator;
    }

    public void setId_operator(Integer id_operator) {
        this.id_operator = id_operator;
    }

    public String getPhone_prefix() {
        return phone_prefix;
    }

    public void setPhone_prefix(String phone_prefix) {
        this.phone_prefix = phone_prefix;
    }

    public String getPhone_number() {
        return phone_number;
    }

    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number;
    }

    @Override
    public Field[] getFieldsOrdered() throws BeanException {
        try {
            Class type = this.getClass();
            Field[] fields = {
                    type.getDeclaredField("id"),
                    type.getDeclaredField("id_operator"),
                    type.getDeclaredField("phone_prefix"),
                    type.getDeclaredField("phone_number"),
            };
            for (Field field: fields) {
                field.setAccessible(true);
            }
            return fields;
        }catch (Exception e){
            throw new BeanException(e);
        }
    }

    public List<String> getAutoGeneratedFields() throws BeanException{
        List<String> strings = new ArrayList<>();
        strings.add("id");
        return strings;
    }

    @Override
    public phone setNotAutoGeneratedFields(Map<String, String> fieldValues) {
        id_operator = Integer.valueOf(fieldValues.get("id_operator"));
        phone_prefix = fieldValues.get("phone_prefix");
        phone_number = fieldValues.get("phone_number");
        return this;
    }

    private Integer id;
    private Integer id_operator;
    private String phone_prefix;
    private String phone_number;
}
