package main.com.bsuir.autoservice.bean.impl;

import main.com.bsuir.autoservice.bean.Bean;
import main.com.bsuir.autoservice.bean.exception.BeanException;
import main.com.bsuir.autoservice.bean.impl.backup.discount;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class shop_product extends Bean{

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId_shop() {
        return id_shop;
    }

    public void setId_shop(Integer id_shop) {
        this.id_shop = id_shop;
    }

    public Integer getId_product() {
        return id_product;
    }

    public void setId_product(Integer id_product) {
        this.id_product = id_product;
    }

    public Integer getAmount_available() {
        return amount_available;
    }

    public void setAmount_available(Integer amount_available) {
        this.amount_available = amount_available;
    }

    public Integer getAmount_reserved() {
        return amount_reserved;
    }

    public void setAmount_reserved(Integer amount_reserved) {
        this.amount_reserved = amount_reserved;
    }

    @Override
    public Field[] getFieldsOrdered() throws BeanException {
        try {
            Class type = this.getClass();
            Field[] fields = {
                    type.getDeclaredField("id"),
                    type.getDeclaredField("id_shop"),
                    type.getDeclaredField("id_product"),
                    type.getDeclaredField("amount_available"),
                    type.getDeclaredField("amount_reserved"),
            };
            for (Field field: fields) {
                field.setAccessible(true);
            }
            return fields;
        }catch (Exception e){
            throw new BeanException(e);
        }
    }

    public List<String> getAutoGeneratedFields() throws BeanException{
        List<String> strings = new ArrayList<>();
        strings.add("id");
        return strings;
    }

    @Override
    public shop_product setFields(Map<String, String> fieldValues) {
        id = Integer.valueOf(fieldValues.get("id"));
        id_shop = Integer.valueOf(fieldValues.get("id_shop"));
        id_product = Integer.valueOf(fieldValues.get("id_product"));
        amount_available = Integer.valueOf(fieldValues.get("amount_available"));
        amount_reserved = Integer.valueOf(fieldValues.get("amount_reserved"));
        return this;
    }

    private Integer id;
    private Integer id_shop;
    private Integer id_product;
    private Integer amount_available;
    private Integer amount_reserved;
}
