package main.com.bsuir.autoservice.bean.impl;

import main.com.bsuir.autoservice.bean.Bean;
import main.com.bsuir.autoservice.bean.exception.BeanException;


import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class shop extends Bean{

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId_address() {
        return id_address;
    }

    public void setId_address(Integer id_address) {
        this.id_address = id_address;
    }

    public Integer getId_manager() {
        return id_manager;
    }

    public void setId_manager(Integer id_manager) {
        this.id_manager = id_manager;
    }

    @Override
    public Field[] getFieldsOrdered() throws BeanException {
        try {
            Class type = this.getClass();
            Field[] fields = {
                    type.getDeclaredField("id"),
                    type.getDeclaredField("id_address"),
                    type.getDeclaredField("id_manager"),
            };
            for (Field field: fields) {
                field.setAccessible(true);
            }
            return fields;
        }catch (Exception e){
            throw new BeanException(e);
        }
    }

    public List<String> getAutoGeneratedFields() throws BeanException{
        List<String> strings = new ArrayList<>();
        strings.add("id");
        return strings;
    }

    @Override
    public shop setNotAutoGeneratedFields(Map<String, String> fieldValues) {
        id_address = Integer.valueOf(fieldValues.get("id_address"));
        id_manager = Integer.valueOf(fieldValues.get("id_manager"));
        return this;
    }

    private Integer id;
    private Integer id_address;
    private Integer id_manager;
}
