package main.com.bsuir.notepads.command.crud.get;

import com.google.inject.Inject;
import main.com.bsuir.notepads.bean.Bean;
import main.com.bsuir.notepads.binding.annotation.Default;
import main.com.bsuir.notepads.command.ICommand;
import main.com.bsuir.notepads.command.exception.CommandException;
import main.com.bsuir.notepads.command.param.BeanAddPageInfo;
import main.com.bsuir.notepads.service.unitOfWork.IServiceUnitOfWork;

import java.util.Map;

public class GetBeanAddPageCommand implements ICommand<BeanAddPageInfo> {

    @Inject
    public GetBeanAddPageCommand(@Default IServiceUnitOfWork serviceUnitOfWork){
        this.serviceUnitOfWork = serviceUnitOfWork;
    }

    @Override
    public BeanAddPageInfo execute(BeanAddPageInfo beanAddPageInfo)
            throws CommandException {
        try {
            Class<? extends Bean> beanClass = (Class<? extends Bean>)Class.forName(Bean.class.getPackage().getName() + ".impl." + beanAddPageInfo.tableName);
            Bean bean = beanClass.newInstance();
            beanAddPageInfo.fields = bean.getFieldValuesStrings();
            for(Map.Entry<String, String> entry : beanAddPageInfo.defaultValues.entrySet()){
                beanAddPageInfo.fields.put(entry.getKey(), entry.getValue());
            }
            for(String autoField : bean.getAutoGeneratedFields()){
                beanAddPageInfo.fields.remove(autoField);
            }

            beanAddPageInfo.action = "add";
            return beanAddPageInfo;
        }catch (Exception e){
            throw new CommandException(e);
        }
    }

    private final IServiceUnitOfWork serviceUnitOfWork;
}
